-- Task1
CREATE TABLE FRIENDS
(ID SERIAL PRIMARY KEY, NAME VARCHAR(255), AGE INT, HOBBY VARCHAR(255),DEPARTMENT VARCHAR(255));

INSERT INTO FRIENDS(NAME, AGE, HOBBY, DEPARTMENT) VALUES
('AHMED',19,'CRICKET','IT'),
('SAEED',20,'WHATPAD','LABOUR'),
('AFFAN',24,'FOOTBALL','MECHANICAL'),
('ARSAL',30,'SIMPING','HR'),
('SAAIM',32,'COMMUNICATION','DESIGN'),
('ALI',35,NULL,'IT'),
('BUSHRA',36,'IG','HR');

SELECT * FROM FRIENDS WHERE ID=5 OR ID=7;

SELECT * FROM FRIENDS WHERE NAME LIKE 'A%';

SELECT * FROM FRIENDS WHERE AGE>=18;

UPDATE FRIENDS SET AGE='16' WHERE NAME='AHMED';

SELECT * FROM FRIENDS;

SELECT * FROM FRIENDS ORDER BY ID ASC;

SELECT * FROM FRIENDS WHERE AGE>=18;

SELECT * FROM FRIENDS WHERE ID BETWEEN 2 AND 8;

SELECT ID,NAME AS FIRST_NAME, AGE, HOBBY, DEPARTMENT FROM FRIENDS;

UPDATE FRIENDS SET AGE=16 WHERE NAME='ALI';

SELECT DISTINCT AGE FROM FRIENDS;

SELECT * FROM FRIENDS WHERE NAME IS NULL OR AGE IS NULL OR HOBBY IS NULL OR DEPARTMENT IS NULL;

ALTER TABLE FRIENDS ADD COLUMN QUALIFICATION VARCHAR(255), ADD COLUMN EXPERIENCE INT;

UPDATE FRIENDS SET HOBBY='FISHING' WHERE NAME='ALI';

ALTER TABLE FRIENDS DROP COLUMN QUALIFICATION, DROP COLUMN EXPERIENCE;

DROP TABLE FRIENDS;


-- Task2
CREATE TABLE EMPLOYEE_INFO
(EMP_ID INT PRIMARY KEY,NAME VARCHAR(255), AGE INT, DEPARTMENT VARCHAR(255));

CREATE TABLE SALARY
(EMP_ID INT, FOREIGN KEY(EMP_ID) REFERENCES EMPLOYEE_INFO(EMP_ID),SALARY NUMERIC(10,2));

INSERT INTO EMPLOYEE_INFO (Emp_Id, Name, Age, Department) VALUES
(1, 'John Doe', 30, 'Engineering'),(2, 'Jane Smith', 25, 'Marketing'),(3, 'Alice Johnson', 35, 'Finance'),(4, 'Bob Brown', 28, 'HR'),(5, 'Emily Davis', 32, 'Sales');

INSERT INTO SALARY (Emp_Id, Salary) VALUES
(1, 50000.00),(2, 45000.00),(3, 55000.00),(4, 48000.00),(5, 52000.00);

DELETE FROM SALARY WHERE EMP_ID=3;

SELECT * FROM SALARY;

TRUNCATE TABLE SALARY;
TRUNCATE TABLE EMPLOYEE_INFO;

DROP TABLE SALARY CASCADE;
DROP TABLE EMPLOYEE_INFO;

SELECT * FROM EMPLOYEE_INFO;
