CREATE TABLE EMPLOYEES(EMPLOYEE_ID INT, EMPLOYEE_NAME VARCHAR(255), DEPARTMENT_ID INT, FOREIGN KEY(DEPARTMENT_ID) REFERENCES
DEPARTMENTS(DEPARTMENT_ID), SALARY INT, EMAIL VARCHAR(255),
JOINING_DATE DATE, RESIGNING_DATE DATE, BONUS INT);

CREATE TABLE DEPARTMENTS(DEPARTMENT_ID INT PRIMARY KEY, DEPARTMENT_NAME VARCHAR(255),
MANAGER_ID INT, LOCATION VARCHAR(255), BUDGET INT, OBJECTIVES VARCHAR(255));

INSERT INTO EMPLOYEES(EMPLOYEE_ID, EMPLOYEE_NAME, DEPARTMENT_ID, SALARY, EMAIL, JOINING_DATE,RESIGNING_DATE, BONUS) VALUES
(1,'JOHN DOE',101,5000,'JOHNDOE@GMAIL.COM','2022-01-10',NULL,5000),
(2,'JANE SMITH', 102, 60000, 'JANESMITH@GMAIL.COM', '2023-03-15', NULL, 6000),
(3,'ALICE JOHNSON', 103, 55000, 'ALICEJOHNSON@YAHOO.COM','2021-05-21', NULL, 5500);

INSERT INTO DEPARTMENTS(DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION, BUDGET, OBJECTIVES) VALUES
(101,'SALES',1,'NEW YORK', 750000, 'INCREASE IN MARKET SHARE BY 10%'),
(102,'MARKETING',2,'SAN FRANCISCO', 500000, 'ENHANCE ONLINE PRESENCE'),
(103,'FINANCE',3,'CHICAGO',600000, 'REDUCE OPERATIONAL COSTS BY 5%');

INSERT INTO EMPLOYEES(EMPLOYEE_NAME, SALARY, DEPARTMENT_ID) VALUES('EMILY JOHNSON', 65000, 103);

SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;

UPDATE DEPARTMENTS SET MANAGER_ID=4 WHERE DEPARTMENT_ID=103;
UPDATE EMPLOYEES SET RESIGNING_DATE='2024-03-13' WHERE DEPARTMENT_ID=102;

SELECT E.EMPLOYEE_NAME, D.DEPARTMENT_NAME FROM EMPLOYEES E
LEFT JOIN DEPARTMENTS D ON D.DEPARTMENT_ID=E.DEPARTMENT_ID;

SELECT COUNT(*) FROM EMPLOYEES WHERE 
EMAIL LIKE ('%GMAIL.COM');

SELECT EMPLOYEE_NAME AS EMPLOYEE_NAME FROM EMPLOYEES
WHERE EMPLOYEE_NAME LIKE 'A%' OR 
EMPLOYEE_NAME LIKE 'E%' OR 
EMPLOYEE_NAME LIKE 'I%' OR 
EMPLOYEE_NAME LIKE 'O%' OR 
EMPLOYEE_NAME LIKE 'U%';

SELECT DEPARTMENT_ID, AVG(SALARY) AS AVG_SALARY, AVG(BONUS) AS AVG_BONUS
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
ORDER BY AVG_SALARY DESC;

SELECT D.DEPARTMENT_NAME,STRING_AGG(E.EMPLOYEE_NAME,', ')AS EMPLOYEES_WORKING, COUNT(E.EMPLOYEE_ID) AS TOTAL_LEFT
FROM DEPARTMENTS D
LEFT JOIN EMPLOYEES E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
WHERE E.RESIGNING_DATE IS NOT NULL
GROUP BY D.DEPARTMENT_NAME;

SELECT DEPARTMENT_ID, EMPLOYEE_ID, EMPLOYEE_NAME 
FROM EMPLOYEES
WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES e2 WHERE e2.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID)
ORDER BY DEPARTMENT_ID;

SELECT
    (SELECT AVG(SALARY) FROM EMPLOYEES 
     LEFT JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID 
     WHERE LOCATION = 'NEW YORK') 
     - 
    (SELECT AVG(SALARY) FROM EMPLOYEES 
     LEFT JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID 
     WHERE LOCATION = 'SAN FRANCISCO') AS SALARY_DIFF;

-- SELECT YEAR(RESIGNING_DATE) AS RESIGNATION_YEAR, COUNT(*) AS TOTAL_EMPLOYEES
-- FROM EMPLOYEES WHERE RESIGNING_DATE IS NOT NULL GROUP BY YEAR(RESIGNING_DATE);

SELECT * FROM EMPLOYEES WHERE RESIGNING_DATE-JOINING_DATE=
(SELECT MAX(RESIGNING_DATE-JOINING_DATE) FROM EMPLOYEES);

SELECT DEPARTMENT_NAME FROM DEPARTMENTS WHERE DEPARTMENT_ID=(SELECT DEPARTMENT_ID FROM EMPLOYEES WHERE EMPLOYEE_NAME='ALICE JOHNSON');

SELECT * FROM EMPLOYEES WHERE BONUS>(SELECT SALARY)

SELECT * FROM EMPLOYEES WHERE EXTRACT( YEAR FROM RESIGNING_DATE)=EXTRACT( YEAR FROM CURRENT_DATE)-1;

SELECT EMPLOYEE_NAME
FROM EMPLOYEES
WHERE JOINING_DATE > '2023-01-01';

DROP TABLE DEPARTMENTS CASCADE;
DROP TABLE EMPLOYEES CASCADE;
